server:
  port: 8082

spring:
  application:
    name: country-service

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      name: localhost