server:
  port: 8081

spring:
  application:
    name: gateway-service

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  routes:
    country-service:
      path: /country-service/**
      serviceId: country-service
      stripPrefix: true
    country-db-service:
      path: /country-db-service/**
      serviceId: country-db-service
      stripPrefix: true

ribbon:
  ConnectTimeout: 120000
  ReadTimeout: 120000

