server:
  port: 8083

spring:
  application:
    name: country-db-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      name: localhost