server:
  port: 8081

spring:
  application:
    name: gateway-service

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

zuul:
#  host:
#    connect-timeout-millis: 5000000
#    socket-timeout-millis: 5000000
  sensitiveHeaders:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    country-service:
      path: /country-service/**
      serviceId: country-service
      stripPrefix: true
    country-db-service:
      path: /country-db-service/**
      serviceId: country-db-service
      stripPrefix: true
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000000
            
           
ribbon:
  ConnectTimeout: 1000000
  ReadTimeout: 1000000  

